config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  devise_for :users, controllers: {   registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end

  root to: 'home#top'
  get 'home/about'
  resources :users,only: [:show,:index,:edit,:update] do
  	member do
      get :following, :followers
    end
  end
  resources :rooms
  
  resources :relationships, only: [:create, :destroy]

  resources :searchs, only: [:index]

end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user, optional: true
    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
        def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
        end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!, only: [:edit,:index,:show]

  def show
  	@book = Book.find(params[:id])
    @newbook = Book.new
    @users = User.all
    @user = @book.user
    @comment = current_user.book_comments.find_by(book_id: params[:book_id])
    @book_comment = BookComment.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
    @user = current_user
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	@book.user_id = current_user.id
    if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
      @user = current_user
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to books_path
    end
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comments.html.erb
<div id="comments">

  <table>
				<% book.book_comments.each do |comment| %>
				<tr>
				<td>
				<%= attachment_image_tag comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg" %><br>
				<%= comment.user.name %>
			    </td>

			    <td>
			    <%= comment.comment %>
			    </td>
			    <% if comment.user.id == current_user.id %>
			    <td><%= link_to "Destroy",book_book_comment_path(book_id: book, id: comment), method: :delete, remote: true, class: "btn-sm btn-danger" %>
			    </td>

			    <%end%>
			    </tr>
			    <%end%>

  </table>
	    	<%= form_with(model: [book, book_comment], remote: true ) do |f| %>
	    	<div class= "row">
	    		<div class="col-xs-9">
	    			<%= f.text_area :comment, rows:'5', class:"form-control",placeholder:"comments" %>
	    		</div>
	        </div>
	        <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
	        <%end%>
	    </div>

app/views/books/_newform.html.erb
<%= form_for(@book) do |f| %>
	<div class="field row">
		<% if @book.errors.any? %>
   <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
   <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="container"> 
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>
	<div id=booklist>
    <div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user.id) do %>
						<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg" %>
						<% end %>
					</td>
					<td><%= link_to book.title,book_path(book.id) %></td>
					<td><%= book.body %></td>
                    
			      <td>
					<div id="favorites_buttons_<%= book.id %>">
					<%= render partial: 'favorites/favorite', locals: { book: book} %>
				    </div>
				   </td>
				   <td>
				   	<div id="comments_count">
				   	コメント：<%= book.book_comments.count %>
				   </div>
				   </td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
    </div>

	
</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">


		<h2>User info</h2>
		<%= render 'users/profile' %>

		<h2>New book</h2>
    <%= form_for(@newbook) do |f| %>
       <% if @book.errors.any? %>
       <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
       <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <%= f.submit 'Create Book' %>
        <% end %>

	</div>

	<div id= "bookdetail">

<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user.id) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%=link_to user_path(@book.user.id) do%>
                    <%= @user.name %>
                    <%end%>
                    </td>
					<td><%= @book.title %></td>
					<td><%= @book.body %></td>
					<% if @user.id == current_user.id %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<%end%>
					<td>
					<div id="favorites_buttons_<%= @book.id %>">
					<%= render partial: 'favorites/favorite', locals: { book: @book} %>
				    </div>
				   </td>
				   <td>
				   	<div id="comments_count">
				   		コメント：<%= @book.book_comments.count %>
				   	</div>
				   </td>
				</tr>
			</table>
			<%= render partial: 'books/comments', locals: { book: @book, book_comment: @book_comment} %>
		</div>
	</div>
</div>

</div>